name: Build Client

# Trigger the workflow on push to the main branch or on pull requests.
on:
  push:
    branches:
      - main

# Define the jobs to run
jobs:
  build:
    # Environment the job runs on (ubuntu-latest for Linux)
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js to the specified version (you can change this version)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x' # Use the Node version that suits your project

      # Install dependencies
      - name: Install Dependencies
        working-directory: ./client
        run: npm install

      # Run the build command
      - name: Build the Client
        working-directory: ./client
        run: npm run build

      # Save the build output as an artifact (optional)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: client-build
          path: ./client/build # Or ./dist for Vue/Angular
